syntax = "proto3";

package auth;

import "validate/validate.proto";
import "user/user.proto";
import "google/protobuf/timestamp.proto";


option go_package = "github.com/MyProject273/Join_Love/pb/auth";

message LoginRequest {
  string email = 1 [
    (validate.rules).string = {
      email: true,
      max_len: 100
    }
  ];

  string password = 2 [
    (validate.rules).string = {
      min_len: 6,
      max_len: 50
    }
  ];
}

message LoginResponse {
  user.User user = 1;
  string AccessToken = 2;
  string RefreshToken = 3;
  google.protobuf.Timestamp access_token_expires_at = 4;
  google.protobuf.Timestamp refresh_token_expires_at = 5;
}

