// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	ID        pgtype.UUID      `json:"id"`
	BlockerID pgtype.UUID      `json:"blocker_id"`
	BlockedID pgtype.UUID      `json:"blocked_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	CreatedBy pgtype.UUID      `json:"created_by"`
}

type Like struct {
	ID         pgtype.UUID      `json:"id"`
	FromUserID pgtype.UUID      `json:"from_user_id"`
	ToUserID   pgtype.UUID      `json:"to_user_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
	CreatedBy  pgtype.UUID      `json:"created_by"`
}

type Match struct {
	ID        pgtype.UUID      `json:"id"`
	User1ID   pgtype.UUID      `json:"user1_id"`
	User2ID   pgtype.UUID      `json:"user2_id"`
	MatchedAt pgtype.Timestamp `json:"matched_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	CreatedBy pgtype.UUID      `json:"created_by"`
}

type Message struct {
	ID        pgtype.UUID      `json:"id"`
	MatchID   pgtype.UUID      `json:"match_id"`
	SenderID  pgtype.UUID      `json:"sender_id"`
	Content   string           `json:"content"`
	SentAt    pgtype.Timestamp `json:"sent_at"`
	IsRead    bool             `json:"is_read"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	CreatedBy pgtype.UUID      `json:"created_by"`
}

type MessageAttachment struct {
	ID         pgtype.UUID      `json:"id"`
	MessageID  pgtype.UUID      `json:"message_id"`
	FileUrl    string           `json:"file_url"`
	FileType   string           `json:"file_type"`
	UploadedAt pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
	CreatedBy  pgtype.UUID      `json:"created_by"`
}

type Notification struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Type      string           `json:"type"`
	Message   string           `json:"message"`
	IsRead    bool             `json:"is_read"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	CreatedBy pgtype.UUID      `json:"created_by"`
}

type Payment struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	SubscriptionID pgtype.UUID      `json:"subscription_id"`
	Amount         pgtype.Numeric   `json:"amount"`
	PaymentMethod  string           `json:"payment_method"`
	PaymentStatus  string           `json:"payment_status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedBy      pgtype.UUID      `json:"created_by"`
}

type Photo struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	ImageUrl  string           `json:"image_url"`
	IsMain    bool             `json:"is_main"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	CreatedBy pgtype.UUID      `json:"created_by"`
}

type PrivacySetting struct {
	ID                          pgtype.UUID      `json:"id"`
	UserID                      pgtype.UUID      `json:"user_id"`
	ShowAge                     bool             `json:"show_age"`
	ShowDistance                bool             `json:"show_distance"`
	AllowMessagesFromNonMatches bool             `json:"allow_messages_from_non_matches"`
	CreatedAt                   pgtype.Timestamp `json:"created_at"`
	UpdatedAt                   pgtype.Timestamp `json:"updated_at"`
	DeletedAt                   pgtype.Timestamp `json:"deleted_at"`
	CreatedBy                   pgtype.UUID      `json:"created_by"`
}

type Report struct {
	ID         pgtype.UUID      `json:"id"`
	ReporterID pgtype.UUID      `json:"reporter_id"`
	ReportedID pgtype.UUID      `json:"reported_id"`
	Reason     string           `json:"reason"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
	CreatedBy  pgtype.UUID      `json:"created_by"`
}

type Subscription struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	PlanName  string           `json:"plan_name"`
	Price     pgtype.Numeric   `json:"price"`
	StartedAt pgtype.Timestamp `json:"started_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	IsActive  bool             `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	CreatedBy pgtype.UUID      `json:"created_by"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	UserName     string           `json:"user_name"`
	Email        string           `json:"email"`
	Phone        *string          `json:"phone"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	FullName     *string          `json:"full_name"`
	Gender       *string          `json:"gender"`
	Birthdate    pgtype.Date      `json:"birthdate"`
	AvatarUrl    *string          `json:"avatar_url"`
	Bio          *string          `json:"bio"`
	IsActive     bool             `json:"is_active"`
	IsVerified   bool             `json:"is_verified"`
	LastLogin    pgtype.Timestamp `json:"last_login"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	CreatedBy    pgtype.UUID      `json:"created_by"`
}

type UserActivity struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Action    string           `json:"action"`
	Metadata  *string          `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	CreatedBy pgtype.UUID      `json:"created_by"`
}

type UserLocation struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Latitude  pgtype.Numeric   `json:"latitude"`
	Longitude pgtype.Numeric   `json:"longitude"`
	City      *string          `json:"city"`
	Country   *string          `json:"country"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	CreatedBy pgtype.UUID      `json:"created_by"`
}

type UserPreference struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	PreferredGender *string          `json:"preferred_gender"`
	MinAge          *int32           `json:"min_age"`
	MaxAge          *int32           `json:"max_age"`
	MaxDistanceKm   *int32           `json:"max_distance_km"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
	CreatedBy       pgtype.UUID      `json:"created_by"`
}

type UserProfile struct {
	ID               pgtype.UUID      `json:"id"`
	UserID           pgtype.UUID      `json:"user_id"`
	JobTitle         *string          `json:"job_title"`
	Education        *string          `json:"education"`
	Interests        *string          `json:"interests"`
	RelationshipGoal *string          `json:"relationship_goal"`
	Religion         *string          `json:"religion"`
	Smoking          *string          `json:"smoking"`
	Drinking         *string          `json:"drinking"`
	HeightCm         *int32           `json:"height_cm"`
	WeightKg         *int32           `json:"weight_kg"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
	CreatedBy        pgtype.UUID      `json:"created_by"`
}
