// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ===============================
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	// ===============================
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CheckUserVerified(ctx context.Context, id pgtype.UUID) (bool, error)
	// ===============================
	CreatePermission(ctx context.Context, name string) (Permission, error)
	CreateRole(ctx context.Context, name string) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeletePermission(ctx context.Context, id int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetListUser(ctx context.Context, arg GetListUserParams) ([]User, error)
	GetPermissionByID(ctx context.Context, id int64) (Permission, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPermissionsByRole(ctx context.Context, roleID int64) ([]Permission, error)
	ListPermissionsByUser(ctx context.Context, userID pgtype.UUID) ([]Permission, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListRolesByUser(ctx context.Context, userID pgtype.UUID) ([]Role, error)
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserActiveStatus(ctx context.Context, arg UpdateUserActiveStatusParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpdateUserVerifiedStatus(ctx context.Context, arg UpdateUserVerifiedStatusParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
