// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
  user_id,
  job_title,
  education,
  interests,
  relationship_goal,
  religion,
  smoking,
  drinking,
  height_cm,
  weight_kg,
  created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, job_title, education, interests, relationship_goal, religion, smoking, drinking, height_cm, weight_kg, created_at, updated_at, deleted_at, created_by
`

type CreateUserProfileParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	JobTitle         *string     `json:"job_title"`
	Education        *string     `json:"education"`
	Interests        *string     `json:"interests"`
	RelationshipGoal *string     `json:"relationship_goal"`
	Religion         *string     `json:"religion"`
	Smoking          *string     `json:"smoking"`
	Drinking         *string     `json:"drinking"`
	HeightCm         *int32      `json:"height_cm"`
	WeightKg         *int32      `json:"weight_kg"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.JobTitle,
		arg.Education,
		arg.Interests,
		arg.RelationshipGoal,
		arg.Religion,
		arg.Smoking,
		arg.Drinking,
		arg.HeightCm,
		arg.WeightKg,
		arg.CreatedBy,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobTitle,
		&i.Education,
		&i.Interests,
		&i.RelationshipGoal,
		&i.Religion,
		&i.Smoking,
		&i.Drinking,
		&i.HeightCm,
		&i.WeightKg,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteUserProfile = `-- name: DeleteUserProfile :exec
UPDATE user_profiles
SET deleted_at = now()
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUserProfile(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserProfile, userID)
	return err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, user_id, job_title, education, interests, relationship_goal, religion, smoking, drinking, height_cm, weight_kg, created_at, updated_at, deleted_at, created_by
FROM user_profiles
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobTitle,
		&i.Education,
		&i.Interests,
		&i.RelationshipGoal,
		&i.Religion,
		&i.Smoking,
		&i.Drinking,
		&i.HeightCm,
		&i.WeightKg,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles
SET
  job_title = COALESCE($2, job_title),
  education = COALESCE($3, education),
  interests = COALESCE($4, interests),
  relationship_goal = COALESCE($5, relationship_goal),
  religion = COALESCE($6, religion),
  smoking = COALESCE($7, smoking),
  drinking = COALESCE($8, drinking),
  height_cm = COALESCE($9, height_cm),
  weight_kg = COALESCE($10, weight_kg),
  updated_at = now()
WHERE user_id = $1 AND deleted_at IS NULL
RETURNING id, user_id, job_title, education, interests, relationship_goal, religion, smoking, drinking, height_cm, weight_kg, created_at, updated_at, deleted_at, created_by
`

type UpdateUserProfileParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	JobTitle         *string     `json:"job_title"`
	Education        *string     `json:"education"`
	Interests        *string     `json:"interests"`
	RelationshipGoal *string     `json:"relationship_goal"`
	Religion         *string     `json:"religion"`
	Smoking          *string     `json:"smoking"`
	Drinking         *string     `json:"drinking"`
	HeightCm         *int32      `json:"height_cm"`
	WeightKg         *int32      `json:"weight_kg"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.JobTitle,
		arg.Education,
		arg.Interests,
		arg.RelationshipGoal,
		arg.Religion,
		arg.Smoking,
		arg.Drinking,
		arg.HeightCm,
		arg.WeightKg,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobTitle,
		&i.Education,
		&i.Interests,
		&i.RelationshipGoal,
		&i.Religion,
		&i.Smoking,
		&i.Drinking,
		&i.HeightCm,
		&i.WeightKg,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}
