// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserVerified = `-- name: CheckUserVerified :one
SELECT is_verified
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CheckUserVerified(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserVerified, id)
	var is_verified bool
	err := row.Scan(&is_verified)
	return is_verified, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    user_name
) VALUES (
    $1,$2,$3
)
RETURNING id, user_name, email, phone, password_hash, role, full_name, gender, birthdate, avatar_url, bio, is_active, is_verified, last_login, created_at, updated_at, deleted_at, created_by
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	UserName     string `json:"user_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.UserName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Gender,
		&i.Birthdate,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getListUser = `-- name: GetListUser :many
SELECT id, user_name, email, phone, password_hash, role, full_name, gender, birthdate, avatar_url, bio, is_active, is_verified, last_login, created_at, updated_at, deleted_at, created_by FROM  users 
LIMIT $1
OFFSET $2
`

type GetListUserParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetListUser(ctx context.Context, arg GetListUserParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getListUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.Role,
			&i.FullName,
			&i.Gender,
			&i.Birthdate,
			&i.AvatarUrl,
			&i.Bio,
			&i.IsActive,
			&i.IsVerified,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, user_name, email, phone, password_hash, role, full_name, gender, birthdate, avatar_url, bio, is_active, is_verified, last_login, created_at, updated_at, deleted_at, created_by FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Gender,
		&i.Birthdate,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_name, email, phone, password_hash, role, full_name, gender, birthdate, avatar_url, bio, is_active, is_verified, last_login, created_at, updated_at, deleted_at, created_by FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Gender,
		&i.Birthdate,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET user_name = COALESCE($1, user_name),
    phone = COALESCE($2, phone),
    full_name = COALESCE($3, full_name),
    gender = COALESCE($4, gender),
    birthdate = COALESCE($5, birthdate),
    avatar_url = COALESCE($6, avatar_url),
    bio = COALESCE($7, bio)
WHERE id = $8
RETURNING id, user_name, email, phone, password_hash, role, full_name, gender, birthdate, avatar_url, bio, is_active, is_verified, last_login, created_at, updated_at, deleted_at, created_by
`

type UpdateUserParams struct {
	UserName  *string     `json:"user_name"`
	Phone     *string     `json:"phone"`
	FullName  *string     `json:"full_name"`
	Gender    *string     `json:"gender"`
	Birthdate pgtype.Date `json:"birthdate"`
	AvatarUrl *string     `json:"avatar_url"`
	Bio       *string     `json:"bio"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserName,
		arg.Phone,
		arg.FullName,
		arg.Gender,
		arg.Birthdate,
		arg.AvatarUrl,
		arg.Bio,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Gender,
		&i.Birthdate,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateUserActiveStatus = `-- name: UpdateUserActiveStatus :one
UPDATE users
SET is_active = $1
WHERE id = $2
RETURNING id, user_name, email, phone, password_hash, role, full_name, gender, birthdate, avatar_url, bio, is_active, is_verified, last_login, created_at, updated_at, deleted_at, created_by
`

type UpdateUserActiveStatusParams struct {
	IsActive bool        `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserActiveStatus(ctx context.Context, arg UpdateUserActiveStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserActiveStatus, arg.IsActive, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Gender,
		&i.Birthdate,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
Update users
SET last_login = $1
WHERE id = $2
`

type UpdateUserLastLoginParams struct {
	LastLogin pgtype.Timestamp `json:"last_login"`
	ID        pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.LastLogin, arg.ID)
	return err
}

const updateUserVerifiedStatus = `-- name: UpdateUserVerifiedStatus :one
UPDATE users
SET is_verified = $1
WHERE id = $2
RETURNING id, user_name, email, phone, password_hash, role, full_name, gender, birthdate, avatar_url, bio, is_active, is_verified, last_login, created_at, updated_at, deleted_at, created_by
`

type UpdateUserVerifiedStatusParams struct {
	IsVerified bool        `json:"is_verified"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserVerifiedStatus(ctx context.Context, arg UpdateUserVerifiedStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserVerifiedStatus, arg.IsVerified, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Gender,
		&i.Birthdate,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}
