// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: auth/rcp_signup.proto

package auth

import (
	user "github.com/MyProject273/Join_Love/pb/user"
	_ "github.com/MyProject273/Join_Love/pb/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_auth_rcp_signup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rcp_signup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_auth_rcp_signup_proto_rawDescGZIP(), []int{0}
}

func (x *SignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *user.User             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_auth_rcp_signup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rcp_signup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_auth_rcp_signup_proto_rawDescGZIP(), []int{1}
}

func (x *SignupResponse) GetUser() *user.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_auth_rcp_signup_proto protoreflect.FileDescriptor

const file_auth_rcp_signup_proto_rawDesc = "" +
	"\n" +
	"\x15auth/rcp_signup.proto\x12\x04auth\x1a\x17validate/validate.proto\x1a\x0fuser/user.proto\"\xa8\x01\n" +
	"\rSignupRequest\x12\x1f\n" +
	"\x05email\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x18d`\x01R\x05email\x12=\n" +
	"\bpassword\x18\x02 \x01(\tB!\xfaB\x1er\x1c\x10\x062\x18^[a-zA-Z0-9@$!%*?&]{6,}$R\bpassword\x127\n" +
	"\tuser_name\x18\x03 \x01(\tB\x1a\xfaB\x17r\x15\x10\x03\x18\x142\x0f^[a-zA-Z0-9_]+$R\buserName\"0\n" +
	"\x0eSignupResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04userB+Z)github.com/MyProject273/Join_Love/pb/authb\x06proto3"

var (
	file_auth_rcp_signup_proto_rawDescOnce sync.Once
	file_auth_rcp_signup_proto_rawDescData []byte
)

func file_auth_rcp_signup_proto_rawDescGZIP() []byte {
	file_auth_rcp_signup_proto_rawDescOnce.Do(func() {
		file_auth_rcp_signup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_rcp_signup_proto_rawDesc), len(file_auth_rcp_signup_proto_rawDesc)))
	})
	return file_auth_rcp_signup_proto_rawDescData
}

var file_auth_rcp_signup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_rcp_signup_proto_goTypes = []any{
	(*SignupRequest)(nil),  // 0: auth.SignupRequest
	(*SignupResponse)(nil), // 1: auth.SignupResponse
	(*user.User)(nil),      // 2: user.User
}
var file_auth_rcp_signup_proto_depIdxs = []int32{
	2, // 0: auth.SignupResponse.user:type_name -> user.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_rcp_signup_proto_init() }
func file_auth_rcp_signup_proto_init() {
	if File_auth_rcp_signup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_rcp_signup_proto_rawDesc), len(file_auth_rcp_signup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_rcp_signup_proto_goTypes,
		DependencyIndexes: file_auth_rcp_signup_proto_depIdxs,
		MessageInfos:      file_auth_rcp_signup_proto_msgTypes,
	}.Build()
	File_auth_rcp_signup_proto = out.File
	file_auth_rcp_signup_proto_goTypes = nil
	file_auth_rcp_signup_proto_depIdxs = nil
}
