// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user/profile/rcp_profile.proto

package profile

import (
	_ "github.com/MyProject273/Join_Love/pb/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_user_profile_rcp_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_rcp_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_profile_rcp_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateUserProfileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobTitle         string                 `protobuf:"bytes,2,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Education        string                 `protobuf:"bytes,3,opt,name=education,proto3" json:"education,omitempty"`
	Interests        string                 `protobuf:"bytes,4,opt,name=interests,proto3" json:"interests,omitempty"`
	RelationshipGoal string                 `protobuf:"bytes,5,opt,name=relationship_goal,json=relationshipGoal,proto3" json:"relationship_goal,omitempty"`
	Religion         string                 `protobuf:"bytes,6,opt,name=religion,proto3" json:"religion,omitempty"`
	Smoking          string                 `protobuf:"bytes,7,opt,name=smoking,proto3" json:"smoking,omitempty"`
	Drinking         string                 `protobuf:"bytes,8,opt,name=drinking,proto3" json:"drinking,omitempty"`
	HeightCm         int32                  `protobuf:"varint,9,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	WeightKg         int32                  `protobuf:"varint,10,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateUserProfileRequest) Reset() {
	*x = CreateUserProfileRequest{}
	mi := &file_user_profile_rcp_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileRequest) ProtoMessage() {}

func (x *CreateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_rcp_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_profile_rcp_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserProfileRequest) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *CreateUserProfileRequest) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *CreateUserProfileRequest) GetInterests() string {
	if x != nil {
		return x.Interests
	}
	return ""
}

func (x *CreateUserProfileRequest) GetRelationshipGoal() string {
	if x != nil {
		return x.RelationshipGoal
	}
	return ""
}

func (x *CreateUserProfileRequest) GetReligion() string {
	if x != nil {
		return x.Religion
	}
	return ""
}

func (x *CreateUserProfileRequest) GetSmoking() string {
	if x != nil {
		return x.Smoking
	}
	return ""
}

func (x *CreateUserProfileRequest) GetDrinking() string {
	if x != nil {
		return x.Drinking
	}
	return ""
}

func (x *CreateUserProfileRequest) GetHeightCm() int32 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *CreateUserProfileRequest) GetWeightKg() int32 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *CreateUserProfileRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type UpdateUserProfileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobTitle         *string                `protobuf:"bytes,2,opt,name=job_title,json=jobTitle,proto3,oneof" json:"job_title,omitempty"`
	Education        *string                `protobuf:"bytes,3,opt,name=education,proto3,oneof" json:"education,omitempty"`
	Interests        *string                `protobuf:"bytes,4,opt,name=interests,proto3,oneof" json:"interests,omitempty"`
	RelationshipGoal *string                `protobuf:"bytes,5,opt,name=relationship_goal,json=relationshipGoal,proto3,oneof" json:"relationship_goal,omitempty"`
	Religion         *string                `protobuf:"bytes,6,opt,name=religion,proto3,oneof" json:"religion,omitempty"`
	Smoking          *string                `protobuf:"bytes,7,opt,name=smoking,proto3,oneof" json:"smoking,omitempty"`
	Drinking         *string                `protobuf:"bytes,8,opt,name=drinking,proto3,oneof" json:"drinking,omitempty"`
	HeightCm         *int32                 `protobuf:"varint,9,opt,name=height_cm,json=heightCm,proto3,oneof" json:"height_cm,omitempty"`
	WeightKg         *int32                 `protobuf:"varint,10,opt,name=weight_kg,json=weightKg,proto3,oneof" json:"weight_kg,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_user_profile_rcp_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_rcp_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_profile_rcp_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetJobTitle() string {
	if x != nil && x.JobTitle != nil {
		return *x.JobTitle
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetEducation() string {
	if x != nil && x.Education != nil {
		return *x.Education
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetInterests() string {
	if x != nil && x.Interests != nil {
		return *x.Interests
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetRelationshipGoal() string {
	if x != nil && x.RelationshipGoal != nil {
		return *x.RelationshipGoal
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetReligion() string {
	if x != nil && x.Religion != nil {
		return *x.Religion
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetSmoking() string {
	if x != nil && x.Smoking != nil {
		return *x.Smoking
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetDrinking() string {
	if x != nil && x.Drinking != nil {
		return *x.Drinking
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetHeightCm() int32 {
	if x != nil && x.HeightCm != nil {
		return *x.HeightCm
	}
	return 0
}

func (x *UpdateUserProfileRequest) GetWeightKg() int32 {
	if x != nil && x.WeightKg != nil {
		return *x.WeightKg
	}
	return 0
}

type DeleteUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserProfileRequest) Reset() {
	*x = DeleteUserProfileRequest{}
	mi := &file_user_profile_rcp_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserProfileRequest) ProtoMessage() {}

func (x *DeleteUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_rcp_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_profile_rcp_profile_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserProfileResponse) Reset() {
	*x = DeleteUserProfileResponse{}
	mi := &file_user_profile_rcp_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserProfileResponse) ProtoMessage() {}

func (x *DeleteUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_rcp_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_profile_rcp_profile_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserProfileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobTitle         string                 `protobuf:"bytes,3,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Education        string                 `protobuf:"bytes,4,opt,name=education,proto3" json:"education,omitempty"`
	Interests        string                 `protobuf:"bytes,5,opt,name=interests,proto3" json:"interests,omitempty"`
	RelationshipGoal string                 `protobuf:"bytes,6,opt,name=relationship_goal,json=relationshipGoal,proto3" json:"relationship_goal,omitempty"`
	Religion         string                 `protobuf:"bytes,7,opt,name=religion,proto3" json:"religion,omitempty"`
	Smoking          string                 `protobuf:"bytes,8,opt,name=smoking,proto3" json:"smoking,omitempty"`
	Drinking         string                 `protobuf:"bytes,9,opt,name=drinking,proto3" json:"drinking,omitempty"`
	HeightCm         int32                  `protobuf:"varint,10,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	WeightKg         int32                  `protobuf:"varint,11,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,15,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserProfileResponse) Reset() {
	*x = UserProfileResponse{}
	mi := &file_user_profile_rcp_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileResponse) ProtoMessage() {}

func (x *UserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_rcp_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileResponse.ProtoReflect.Descriptor instead.
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_profile_rcp_profile_proto_rawDescGZIP(), []int{5}
}

func (x *UserProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfileResponse) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *UserProfileResponse) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *UserProfileResponse) GetInterests() string {
	if x != nil {
		return x.Interests
	}
	return ""
}

func (x *UserProfileResponse) GetRelationshipGoal() string {
	if x != nil {
		return x.RelationshipGoal
	}
	return ""
}

func (x *UserProfileResponse) GetReligion() string {
	if x != nil {
		return x.Religion
	}
	return ""
}

func (x *UserProfileResponse) GetSmoking() string {
	if x != nil {
		return x.Smoking
	}
	return ""
}

func (x *UserProfileResponse) GetDrinking() string {
	if x != nil {
		return x.Drinking
	}
	return ""
}

func (x *UserProfileResponse) GetHeightCm() int32 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *UserProfileResponse) GetWeightKg() int32 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *UserProfileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfileResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserProfileResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *UserProfileResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

var File_user_profile_rcp_profile_proto protoreflect.FileDescriptor

const file_user_profile_rcp_profile_proto_rawDesc = "" +
	"\n" +
	"\x1euser/profile/rcp_profile.proto\x12\aprofile\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x15GetUserProfileRequest\x12%\n" +
	"\auser_id\x18\x01 \x01(\tB\f\xfaB\tr\a\x10$\x18$\xb0\x01\x01R\x06userId\"\xc6\x03\n" +
	"\x18CreateUserProfileRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12$\n" +
	"\tjob_title\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18dR\bjobTitle\x12%\n" +
	"\teducation\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18dR\teducation\x12\x1c\n" +
	"\tinterests\x18\x04 \x01(\tR\tinterests\x124\n" +
	"\x11relationship_goal\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x182R\x10relationshipGoal\x12#\n" +
	"\breligion\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x182R\breligion\x12!\n" +
	"\asmoking\x18\a \x01(\tB\a\xfaB\x04r\x02\x18\x14R\asmoking\x12#\n" +
	"\bdrinking\x18\b \x01(\tB\a\xfaB\x04r\x02\x18\x14R\bdrinking\x12'\n" +
	"\theight_cm\x18\t \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xfa\x01(2R\bheightCm\x12'\n" +
	"\tweight_kg\x18\n" +
	" \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xac\x02(\x14R\bweightKg\x12'\n" +
	"\n" +
	"created_by\x18\v \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tcreatedBy\"\xcc\x04\n" +
	"\x18UpdateUserProfileRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12)\n" +
	"\tjob_title\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18dH\x00R\bjobTitle\x88\x01\x01\x12*\n" +
	"\teducation\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18dH\x01R\teducation\x88\x01\x01\x12!\n" +
	"\tinterests\x18\x04 \x01(\tH\x02R\tinterests\x88\x01\x01\x129\n" +
	"\x11relationship_goal\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x182H\x03R\x10relationshipGoal\x88\x01\x01\x12(\n" +
	"\breligion\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x182H\x04R\breligion\x88\x01\x01\x12&\n" +
	"\asmoking\x18\a \x01(\tB\a\xfaB\x04r\x02\x18\x14H\x05R\asmoking\x88\x01\x01\x12(\n" +
	"\bdrinking\x18\b \x01(\tB\a\xfaB\x04r\x02\x18\x14H\x06R\bdrinking\x88\x01\x01\x12,\n" +
	"\theight_cm\x18\t \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xfa\x01(2H\aR\bheightCm\x88\x01\x01\x12,\n" +
	"\tweight_kg\x18\n" +
	" \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xac\x02(\x14H\bR\bweightKg\x88\x01\x01B\f\n" +
	"\n" +
	"_job_titleB\f\n" +
	"\n" +
	"_educationB\f\n" +
	"\n" +
	"_interestsB\x14\n" +
	"\x12_relationship_goalB\v\n" +
	"\t_religionB\n" +
	"\n" +
	"\b_smokingB\v\n" +
	"\t_drinkingB\f\n" +
	"\n" +
	"_height_cmB\f\n" +
	"\n" +
	"_weight_kg\"=\n" +
	"\x18DeleteUserProfileRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"5\n" +
	"\x19DeleteUserProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa0\x04\n" +
	"\x13UserProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tjob_title\x18\x03 \x01(\tR\bjobTitle\x12\x1c\n" +
	"\teducation\x18\x04 \x01(\tR\teducation\x12\x1c\n" +
	"\tinterests\x18\x05 \x01(\tR\tinterests\x12+\n" +
	"\x11relationship_goal\x18\x06 \x01(\tR\x10relationshipGoal\x12\x1a\n" +
	"\breligion\x18\a \x01(\tR\breligion\x12\x18\n" +
	"\asmoking\x18\b \x01(\tR\asmoking\x12\x1a\n" +
	"\bdrinking\x18\t \x01(\tR\bdrinking\x12\x1b\n" +
	"\theight_cm\x18\n" +
	" \x01(\x05R\bheightCm\x12\x1b\n" +
	"\tweight_kg\x18\v \x01(\x05R\bweightKg\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x0f \x01(\tR\tcreatedByB3Z1github.com/MyProject273/Join_Love/pb/user/profileb\x06proto3"

var (
	file_user_profile_rcp_profile_proto_rawDescOnce sync.Once
	file_user_profile_rcp_profile_proto_rawDescData []byte
)

func file_user_profile_rcp_profile_proto_rawDescGZIP() []byte {
	file_user_profile_rcp_profile_proto_rawDescOnce.Do(func() {
		file_user_profile_rcp_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_profile_rcp_profile_proto_rawDesc), len(file_user_profile_rcp_profile_proto_rawDesc)))
	})
	return file_user_profile_rcp_profile_proto_rawDescData
}

var file_user_profile_rcp_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_profile_rcp_profile_proto_goTypes = []any{
	(*GetUserProfileRequest)(nil),     // 0: profile.GetUserProfileRequest
	(*CreateUserProfileRequest)(nil),  // 1: profile.CreateUserProfileRequest
	(*UpdateUserProfileRequest)(nil),  // 2: profile.UpdateUserProfileRequest
	(*DeleteUserProfileRequest)(nil),  // 3: profile.DeleteUserProfileRequest
	(*DeleteUserProfileResponse)(nil), // 4: profile.DeleteUserProfileResponse
	(*UserProfileResponse)(nil),       // 5: profile.UserProfileResponse
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_user_profile_rcp_profile_proto_depIdxs = []int32{
	6, // 0: profile.UserProfileResponse.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: profile.UserProfileResponse.updated_at:type_name -> google.protobuf.Timestamp
	6, // 2: profile.UserProfileResponse.deleted_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_profile_rcp_profile_proto_init() }
func file_user_profile_rcp_profile_proto_init() {
	if File_user_profile_rcp_profile_proto != nil {
		return
	}
	file_user_profile_rcp_profile_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_profile_rcp_profile_proto_rawDesc), len(file_user_profile_rcp_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_profile_rcp_profile_proto_goTypes,
		DependencyIndexes: file_user_profile_rcp_profile_proto_depIdxs,
		MessageInfos:      file_user_profile_rcp_profile_proto_msgTypes,
	}.Build()
	File_user_profile_rcp_profile_proto = out.File
	file_user_profile_rcp_profile_proto_goTypes = nil
	file_user_profile_rcp_profile_proto_depIdxs = nil
}
