// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user/service_user.proto

package user

import (
	profile "github.com/MyProject273/Join_Love/pb/user/profile"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_service_user_proto protoreflect.FileDescriptor

const file_user_service_user_proto_rawDesc = "" +
	"\n" +
	"\x17user/service_user.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1euser/profile/rcp_profile.proto2\xa6\x06\n" +
	"\vUserService\x12\xc9\x01\n" +
	"\x0eGetUserProfile\x12\x1e.profile.GetUserProfileRequest\x1a\x1c.profile.UserProfileResponse\"y\x92AO\x12\x10Get User Profile\x1a;Retrieve profile information of a specific user by user_id.\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/user_profiles/{user_id}\x12\xaa\x01\n" +
	"\x11CreateUserProfile\x12!.profile.CreateUserProfileRequest\x1a\x1c.profile.UserProfileResponse\"T\x92A1\x12\x13Create User Profile\x1a\x1aCreate a new user profile.\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/user_profiles\x12\xc4\x01\n" +
	"\x11UpdateUserProfile\x12!.profile.UpdateUserProfileRequest\x1a\x1c.profile.UserProfileResponse\"n\x92AA\x12\x13Update User Profile\x1a*Update fields of an existing user profile.\x82\xd3\xe4\x93\x02$:\x01*2\x1f/api/v1/user_profiles/{user_id}\x12\xd6\x01\n" +
	"\x11DeleteUserProfile\x12!.profile.DeleteUserProfileRequest\x1a\".profile.DeleteUserProfileResponse\"z\x92AP\x12\x13Delete User Profile\x1a9Soft delete user profile by setting deleted_at timestamp.\x82\xd3\xe4\x93\x02!*\x1f/api/v1/user_profiles/{user_id}BH\x92A\x1a\x12\x18\n" +
	"\x11JoinLove User API2\x031.0Z)github.com/MyProject273/Join_Love/pb/userb\x06proto3"

var file_user_service_user_proto_goTypes = []any{
	(*profile.GetUserProfileRequest)(nil),     // 0: profile.GetUserProfileRequest
	(*profile.CreateUserProfileRequest)(nil),  // 1: profile.CreateUserProfileRequest
	(*profile.UpdateUserProfileRequest)(nil),  // 2: profile.UpdateUserProfileRequest
	(*profile.DeleteUserProfileRequest)(nil),  // 3: profile.DeleteUserProfileRequest
	(*profile.UserProfileResponse)(nil),       // 4: profile.UserProfileResponse
	(*profile.DeleteUserProfileResponse)(nil), // 5: profile.DeleteUserProfileResponse
}
var file_user_service_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.GetUserProfile:input_type -> profile.GetUserProfileRequest
	1, // 1: user.UserService.CreateUserProfile:input_type -> profile.CreateUserProfileRequest
	2, // 2: user.UserService.UpdateUserProfile:input_type -> profile.UpdateUserProfileRequest
	3, // 3: user.UserService.DeleteUserProfile:input_type -> profile.DeleteUserProfileRequest
	4, // 4: user.UserService.GetUserProfile:output_type -> profile.UserProfileResponse
	4, // 5: user.UserService.CreateUserProfile:output_type -> profile.UserProfileResponse
	4, // 6: user.UserService.UpdateUserProfile:output_type -> profile.UserProfileResponse
	5, // 7: user.UserService.DeleteUserProfile:output_type -> profile.DeleteUserProfileResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_user_proto_init() }
func file_user_service_user_proto_init() {
	if File_user_service_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_user_proto_rawDesc), len(file_user_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_user_proto_goTypes,
		DependencyIndexes: file_user_service_user_proto_depIdxs,
	}.Build()
	File_user_service_user_proto = out.File
	file_user_service_user_proto_goTypes = nil
	file_user_service_user_proto_depIdxs = nil
}
