// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: service_join_love.proto

package joinlove

import (
	context "context"
	auth "github.com/MyProject273/Join_Love/pb/auth"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JoinLove_Login_FullMethodName = "/joinlove.JoinLove/Login"
)

// JoinLoveClient is the client API for JoinLove service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JoinLoveClient interface {
	Login(ctx context.Context, in *auth.LoginRequest, opts ...grpc.CallOption) (*auth.LoginResponse, error)
}

type joinLoveClient struct {
	cc grpc.ClientConnInterface
}

func NewJoinLoveClient(cc grpc.ClientConnInterface) JoinLoveClient {
	return &joinLoveClient{cc}
}

func (c *joinLoveClient) Login(ctx context.Context, in *auth.LoginRequest, opts ...grpc.CallOption) (*auth.LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(auth.LoginResponse)
	err := c.cc.Invoke(ctx, JoinLove_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JoinLoveServer is the server API for JoinLove service.
// All implementations must embed UnimplementedJoinLoveServer
// for forward compatibility.
type JoinLoveServer interface {
	Login(context.Context, *auth.LoginRequest) (*auth.LoginResponse, error)
	mustEmbedUnimplementedJoinLoveServer()
}

// UnimplementedJoinLoveServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJoinLoveServer struct{}

func (UnimplementedJoinLoveServer) Login(context.Context, *auth.LoginRequest) (*auth.LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedJoinLoveServer) mustEmbedUnimplementedJoinLoveServer() {}
func (UnimplementedJoinLoveServer) testEmbeddedByValue()                  {}

// UnsafeJoinLoveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JoinLoveServer will
// result in compilation errors.
type UnsafeJoinLoveServer interface {
	mustEmbedUnimplementedJoinLoveServer()
}

func RegisterJoinLoveServer(s grpc.ServiceRegistrar, srv JoinLoveServer) {
	// If the following call pancis, it indicates UnimplementedJoinLoveServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JoinLove_ServiceDesc, srv)
}

func _JoinLove_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(auth.LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinLoveServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinLove_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinLoveServer).Login(ctx, req.(*auth.LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JoinLove_ServiceDesc is the grpc.ServiceDesc for JoinLove service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JoinLove_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "joinlove.JoinLove",
	HandlerType: (*JoinLoveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _JoinLove_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_join_love.proto",
}
