// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: service_join_love.proto

package joinlove

import (
	auth "github.com/MyProject273/Join_Love/pb/auth"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_join_love_proto protoreflect.FileDescriptor

const file_service_join_love_proto_rawDesc = "" +
	"\n" +
	"\x17service_join_love.proto\x12\bjoinlove\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x14auth/rcp_login.proto2\x90\x01\n" +
	"\bJoinLove\x12\x83\x01\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\"Q\x92A9\x12\fVerify Email\x1a)Use this API to verify user email address\x82\xd3\xe4\x93\x02\x0f\"\r/api/v1/loginBG\x92A\x15\x12\x13\n" +
	"\fJoinLove API2\x031.2Z-github.com/MyProject273/Join_Love/pb/joinloveb\x06proto3"

var file_service_join_love_proto_goTypes = []any{
	(*auth.LoginRequest)(nil),  // 0: auth.LoginRequest
	(*auth.LoginResponse)(nil), // 1: auth.LoginResponse
}
var file_service_join_love_proto_depIdxs = []int32{
	0, // 0: joinlove.JoinLove.Login:input_type -> auth.LoginRequest
	1, // 1: joinlove.JoinLove.Login:output_type -> auth.LoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_join_love_proto_init() }
func file_service_join_love_proto_init() {
	if File_service_join_love_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_join_love_proto_rawDesc), len(file_service_join_love_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_join_love_proto_goTypes,
		DependencyIndexes: file_service_join_love_proto_depIdxs,
	}.Build()
	File_service_join_love_proto = out.File
	file_service_join_love_proto_goTypes = nil
	file_service_join_love_proto_depIdxs = nil
}
