syntax = "proto3";

package user;

import "google/protobuf/timestamp.proto";
import "common/common.proto";

option go_package = "github.com/MyProject273/Join_Love/pb/user";

message User {
  string id = 1;
  string user_name = 2;
  string email = 3;
  optional string phone = 4;
  string role = 5;
  optional string full_name = 6;
  optional string gender = 7;
  google.protobuf.Timestamp birthdate = 8;
  optional string avatar_url = 9;
  optional string bio = 10;
  bool is_active = 11;
  bool is_verified = 12;
  google.protobuf.Timestamp last_login = 13;
  common.AuditFields audit_fields = 14;
}
